### ISSUE TITLE
Add "Manual Configuration" section to credentials

### ISSUE THREAD

**Issue by DavidSouther** [awsdocs/aws-rust-developer-guide-v1#23]
https://github.com/awsdocs/aws-rust-developer-guide-v1/blob/main/doc_source/credentials.md

Add a section describing how to manually configure an SDK Client, without using load_from_env and related.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
