### ISSUE TITLE
Add "WebAssembly" page

### ISSUE THREAD

**Issue by DavidSouther** [awsdocs/aws-rust-developer-guide-v1#24]
After https://github.com/awsdocs/aws-doc-sdk-examples/pull/4325 is merged, add a Web Assembly page discussing Web Assembly & Rust.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
