### ISSUE TITLE
Markdown rendering issue - bold not being applied

### ISSUE THREAD

**Issue by timClicks** [awsdocs/aws-rust-developer-guide-v1#25]
For some reason, the bold syntax used in the Lambda guide isn't being rendered correctly:

Input: 

https://github.com/awsdocs/aws-rust-developer-guide-v1/blob/c46eb397cc6bf1b01c4b81b48c2711efc2679983/doc_source/lambda.md?plain=1#L180

Output:

<img width="742" alt="Screenshot 2023-03-01 at 15 31 21" src="https://user-images.githubusercontent.com/27889/222030052-29759edc-e8a3-413c-81ae-699c18e24220.png">

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
