### ISSUE TITLE
All Rust API reference links in Rust Developer Guide are incorrect

### ISSUE THREAD

**Issue by DavidSouther** [awsdocs/aws-rust-developer-guide-v1#26]
All the Rust API references point to https://docs.rs/releases/search?query=aws-sdk instead of to individual action calls. They should point to specific calls or have verbiage changed to not appear to be more specific.

For example,

> For API details, see Scan in AWS SDK for Rust API reference.
This points to the general link above, but implies it will point to Scan.

(Copied from https://github.com/awsdocs/aws-doc-sdk-examples/issues/4019)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
