### ISSUE TITLE
Getting Started section fixes 

### ISSUE THREAD

**Issue by rcoh** [awsdocs/aws-rust-developer-guide-v1#3]
Getting Started

- [ ] Do we really need to say "DynamoDB (DynamoDB)"
- [ ] It says "S3Reader" even the example is about DynamoDB
- [ ] The example still says "S3 buckets"
- [ ] no need to run clippy (and that clippy invocation is not a good pattern)

**Comment by Doug-AWS** [comment]
It's Amazon DynamoDB (DynamoDB)
The rest should be fixed when I update these files
